# Generated by Django 2.2 on 2020-04-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_text', models.CharField(max_length=50)),
                ('pub_date_text', models.DateTimeField(verbose_name='Date Published:')),
                ('body_text', models.CharField(max_length=400)),
            ],
        ),
    ]
